# sudo: required
# services:
#   - docker

# before_install:
#   - wget -qO- https://toolbelt.heroku.com/install.sh | sh
#   - docker build -t higaguin/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true higaguin/react-test npm test
#
jobs:
  include:
    - stage: deploy to heroku
      language: node_js
      before_install: cd server
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: boring-note-app-api
        on:
          branch: master
    - stage: deply to netlify
      # before_install:
      #   - npm install -g netlify-cli
      language: node_js
      node_js:
        - "stable"
      before_install: cd client
      deploy:
        provider: netlify
        site: $NETLIFY_ID
        auth: $NETLIFY_AUTH
        dir: "dist/"
        edge: true
        prod: true
        on:
          branch: master
